name: Build and publish JS library

on:
  release:
    types: [published]
    tags-ignore:
      - blossom-ext*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node library modules
        id: cache-npm-lib
        uses: actions/cache@v3
        with:
          path: library/node_modules
          key: ${{ runner.os }}-lib-${{ hashFiles('**/library/package-lock.json') }}

      - name: Install library dependencies
        run: npm ci --prefix library
        if: ${{ steps.cache-npm-lib.outputs.cache-hit == 'true' }}

      - name: Build
        run: npm run build --prefix library

      - name: Publish
        run: cd library && npm publish --access public && cd ..
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
