# On each new commit to master, create/update a PR with release
# automatically bumps version and creates changelog as per conventional commits
# https://github.com/google-github-actions/release-please-action
name: Release Github

on:
  push:
    branches:
      - master

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release-lib
        with:
          release-type: node
          path: library
          package-name: 'blossom-js-lib'
          changelog-path: 'library/CHANGELOG.md'
          version-file: 'library/package.json'
          pull-request-title-pattern: 'chore${scope}: release js-lib ${version}'
          monorepo-tags: true
