name: Run tests

on:
  push:
    branches: [master]
    paths-ignore:
      - 'library/**'
  pull_request:
    branches: [master]
    paths-ignore:
      - 'library/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        id: cache-npm-ext
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci
        if: ${{ steps.cache-npm-ext.outputs.cache-hit == 'true' }}

      - name: Lint
        run: npm run lint:check

      - name: Compile Swarm Extension
        run: npm run swarm-ext

      - name: Build
        run: npm run build

      - name: Install fdp-play
        run: npm install -g @fairdatasociety/fdp-play

      - name: Run fdp-play
        run: fdp-play start -d

      - name: Test
        run: npm test
